### ISSUE TITLE
unusably slow on large sets

### ISSUE THREAD

**Issue by tablatronix** [maxazan/jquery-treegrid#11]
In chrome and firefox tested.
With 100 rows of reasonably nested lists, this completely fails to init, don't even try it on anything larger as it freezes.

Some optimization needed here for this to be practical,
There is something wrong with init is seems.

:( was promising

**Comment by maxazan** [comment]
Thank you for your help. Try new release of plugin.
http://maxazan.github.io/jquery-treegrid/examples/example-huge.html

**Comment by dsnoeck** [comment]
Nice improvement. My benchmark of page loading time went from 15 seconds with version 0.2.0 to 7 seconds with v. 0.3.0. Thanks a lot

**Comment by ADSoftTeam** [comment]
> Thank you for your help. Try new release of plugin. http://maxazan.github.io/jquery-treegrid/examples/example-huge.html

This example not working! Don't file ../js/jquery.treegrid.js 

pls - refresh example?
