### ISSUE TITLE
Column hiding based on device size?

### ISSUE THREAD

**Issue by krosoftware** [maxazan/jquery-treegrid#31]
Hello all
I need option where it is possible to define which column(s) are always visible and which are hidden based on device size.
For example, on desktop displayed are all 5 columns
on iPad (portrait) displayed are 3 columns and on phone displayed is only one column, something like it works here:
https://github.com/filamentgroup/tablesaw

I want to pay if someone can add that feature (wanted to write directly to maxazan but can not find any email address?
Than you.

**Comment by maxazan** [comment]
Hey there
You can do this using only bootstrap ability
Demo:
http://maxazan.github.io/jquery-treegrid/examples/example-bootstrap-resize.html
Video:
https://www.youtube.com/watch?v=OofNlTyqRRY

**Comment by krosoftware** [comment]
Hello Maksym
thank you so much but I'm limited to jQuery, because I'm using also
Framework7 (http://www.idangero.us/framework7/) and it is not compatible
with Bootstrap.
Any chance to adopt your treeGrid for jQuery?
Thank you.
Zdravko


2015-07-07 11:02 GMT+02:00 Maksym Pomazan <notifications@github.com>:

**Comment by krosoftware** [comment]
I meant
"Any chance to adopt same feature for jQuery?"?
Thank you.

**Comment by maxazan** [comment]
http://codepen.io/maxazan/pen/Qbmmmd

**Comment by krosoftware** [comment]
Works perfect.
You are the man.
Thank you.

2015-07-07 13:51 GMT+02:00 Maksym Pomazan <notifications@github.com>:
