### ISSUE TITLE
Is there a way to show the tree in collapsed form instead of expended form?

### ISSUE THREAD

**Issue by yuenon** [maxazan/jquery-treegrid#50]
I wonder if we can set some parameters so that tree can be shown as collapsed form by default.  When the user clicks on the icon or node, the tree nodes will be expended.  Thanks!

**Comment by maxazan** [comment]
There is `initialState` parameter in Configuration Settings
Read Configuration Settings

**Comment by yuenon** [comment]
Thanks. It works.
