### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by Belgabad3435** [maxazan/jquery-treegrid#56]
Hi maxazan,
I'm currently trying to use your tool with angular 2, using ng-repeat to populate the grid. I've run into some issues with it. Do you support, or plan to support, angular?
Thanks!

**Comment by maxazan** [comment]
Hi Belgabad,
I'm not sure it's a good idea to use tree grid with angular. They have absolutely different concept. If I were you, I'd try to find treegrid module for angular.

**Comment by Belgabad3435** [comment]
Okay, I'll start looking around for another option. Thanks for your help!
